pipeline{
    agent{
        label 'AGENT-1'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action')
    }

    stages{
        stage('init and plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 60-alb
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        stage('apply or destroy'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 60-alb
                        if [ "${params.ACTION}" == "apply" ]
                        then
                            terraform apply -auto-approve
                        elif [ "${params.ACTION}" == "destroy" ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }

    post{
        always{
            echo "This section run always"
            deleteDir()
        }
    }

}