pipeline{
    agent{
        label 'AGENT-1'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    // global variables
    parameters{
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select action')
    }

    stages{
        // terraform init and plan 
        stage('Init and Plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        // terraform apply or destroy
        stage('APPLY or DESTROY'){
            input{
                message "Should we continue to ${params.ACTION}"
                ok "yes, we should."
            }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 00-vpc
                        if [ "${params.ACTION}" == "apply" ]
                        then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" == "destroy" ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }

        // trigger 10-sg folder
        stage('TRIGGER SG'){
            when {
                expression { params.ACTION == 'apply' }
            }
            steps{
                build job: '10-sg', parameters: [string(name: 'ACTION', value: "apply")], wait: false
            }
        }
    }

    post{
        always{
            echo "This section runs always"
            deleteDir()
        }
    }
}