pipeline{
    agent{
        label 'AGENT-1'
    }

    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters{
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select action')
    }

    stages{
        stage('init and plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 20-bastion
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('apply or destroy'){
            // input {
            //     message "should we continue to ${params.ACTION}"
            //     ok "yes, we should."
            // }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                    cd 20-bastion
                    if [ "${params.ACTION}" == "apply" ]
                    then
                        terraform apply -auto-approve tfplan
                    elif [ "${params.ACTION}" == "destroy" ]
                    then
                        terraform destroy -auto-approve
                    fi
                    """
                }
            }
        }
    }
    post {
        always{
            echo "This section run always"
            deleteDir()
        }
    }
}