pipeline{
    agent{
        label 'AGENT-1'
    }
    
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters{
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select action')
    }

    stages{
        stage('init and plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        // terraform apply or destroy 
        stage('Apply or Destroy'){
            input {
                message "should we continue to ${params.ACTION}"
                ok "yes. we should."
            }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 10-sg
                        if [ "${params.ACTION}" == "apply" ]
                        then
                            terraform apply -auto-approve
                        elif [ "${params.ACTION}" == "destroy" ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }

        // destroy 00-vpc when 10-sg is destroying
        stage('Destroy vpc'){
            when {
                expression { params.ACTION == "destroy" }
            }
            steps{
                build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
            }
        }

        // trigger other pipelines when 10-sg is applied
        stage('parallel'){

            when{
                expression { params.ACTION == 'apply' }
            }

            parallel{
                stage('bastion'){
                    steps{
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('eks'){
                    steps{
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }

                stage('rds'){
                    steps{
                        build job: '30-rds', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }

                stage('ecr'){
                    steps{
                        build job: '70-ecr', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
            }
        }
        stage('Sequential') {
            when {
                expression { params.ACTION == 'apply' }
            }
            stages {
                stage('ACM') {
                    steps {
                        build job: '50-acm', parameters: [string(name: 'ACTION', value: "apply")]
                    }
                }
                stage('ALB') {
                    steps {
                        build job: '60-alb', parameters: [string(name: 'ACTION', value: "apply")], wait: false
                    }
                }
                stage('CDN') {
                    steps {
                        build job: '80-cdn', parameters: [string(name: 'ACTION', value: "apply")], wait: false
                    }
                }
            }
        }
    }

    post{
        always{
            echo "This section runs always"
            deleteDir()
        }
    }
}